### ISSUE TITLE
"Something went wrong..." Message

### ISSUE THREAD

**Issue by Anoaxx** [mWalrus/MapRank#10]
soo... i cant use the plugin cause use of that. It looks like this:
![image](https://github.com/mWalrus/MapRank/assets/64927564/e6f77727-f5a0-4aa4-af30-b74d4dd5af91)

I can provide any information u need. Btw restarting a game or cleaning cache didnt repaired a problem

**Comment by Anoaxx** [comment]
My pursuit for top 10% on every track cant be pursuited cause of it. 

p.s. Have a good day <3

**Comment by mWalrus** [comment]
I'll make sure you can continue ur grind soon :P

**Comment by mWalrus** [comment]
It's up again! Something must have went wrong in the backend :confused: I'll continue to investigate if there is some unhandled case somewhere :slightly_smiling_face:

**Comment by Anoaxx** [comment]
nadeo is planning to add your plugin to the game, thats why they sabotaged your plugin :PPPPPPP
