### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Flaming-Dorito** [mWalrus/MapRank#11]
![image](https://github.com/mWalrus/MapRank/assets/30212627/62e1bd46-6383-44dc-93a7-113f121b0e76)

**Comment by mWalrus** [comment]
yeah, sometimes when nadeo performs maintenance, the api hangs when the leaderboard info isnt available. Fixed now :)

**Comment by mWalrus** [comment]
I'll also update the plugin itself so that it can handle cases like these. For now you'll need to reload the plugin in openplanet. :)
