### ISSUE TITLE
Have a setting so the time lookup button doesn't show by default

### ISSUE THREAD

**Issue by CatzHoekk** [mWalrus/MapRank#7]
I really don't need or want the time lookup when i don't explicitly open it. Having to disable it every time is quite annoying.

Would be nice if that would be a permanent setting.

**Comment by mWalrus** [comment]
Yeah i figured that this could become cumbersome. I'll release an update in the coming days just inverting the option which means it's gonna be disabled by default.

Thanks for the feedback btw :)
